name: Docker Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub (Optional)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: ${{ secrets.DOCKER_USERNAME }}

    - name: Build Docker image
      run: |
        docker build -t pinterest-scraper:${{ github.sha }} .
        docker tag pinterest-scraper:${{ github.sha }} pinterest-scraper:latest

    - name: Save Docker image
      run: |
        docker save pinterest-scraper:latest | gzip > pinterest-scraper.tar.gz

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "pinterest-scraper.tar.gz,docker-compose.yml"
        target: "/home/${{ secrets.USERNAME }}/pinterest-scraper/"

    - name: Deploy on server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/${{ secrets.USERNAME }}/pinterest-scraper
          
          # Create .env file from secrets
          cat > .env << EOF
          DEFAULT_IMAGE_LIMIT=${{ secrets.DEFAULT_IMAGE_LIMIT }}
          MAX_IMAGES_PER_REQUEST=${{ secrets.MAX_IMAGES_PER_REQUEST }}
          PINTEREST_BASE_URL=${{ secrets.PINTEREST_BASE_URL }}
          DEFAULT_SCROLL_COUNT=${{ secrets.DEFAULT_SCROLL_COUNT }}
          WEBSITE_URL=${{ secrets.WEBSITE_URL }}
          PINTEREST_EMAIL=${{ secrets.PINTEREST_EMAIL }}
          PINTEREST_PASSWORD=${{ secrets.PINTEREST_PASSWORD }}
          SCROLL_COUNT=${{ secrets.SCROLL_COUNT }}
          EOF
          
          # Load new Docker image
          docker load < pinterest-scraper.tar.gz
          
          # Stop and remove old containers
          docker-compose down || true
          
          # Start new containers
          docker-compose up -d
          
          # Clean up
          rm pinterest-scraper.tar.gz
          
          # Show container status
          docker-compose ps 
